<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\RegReturns.Domain\RegReturns.Domain.csproj" />
    <ProjectReference Include="..\..\src\RegReturns.Application\RegReturns.Application.csproj" />
    <ProjectReference Include="..\..\src\RegReturns.Infrastructure\RegReturns.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\RegReturns.ServiceDefaults\RegReturns.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\src\RegReturns.Web\RegReturns.Web.csproj" />
    <ProjectReference Include="..\..\src\RegReturns.Api\RegReturns.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>
</Project>
