using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

using Microsoft.Extensions.Options;

using RegReturns.Application.Identity;
using RegReturns.IamBootstrap.Wso2;

namespace RegReturns.IamBootstrap.Steps;

/// <summary>
/// Ensures the portal's OIDC app (plan §4.2): confidential client, code flow with mandatory PKCE S256, JWT access
/// tokens of 300 s, no refresh token, back-channel logout, the user claims the portal reads, and an adaptive script
/// that adds a TOTP step for approvers and administrators (and always for the configured demo users).
/// </summary>
/// <param name="applications">Application management.</param>
/// <param name="options">The tool options.</param>
internal sealed class PortalAppStep(Wso2Applications applications, IOptions<BootstrapOptions> options) : IBootstrapStep
{
    /// <summary>The WSO2 authenticator for the first step (user name and secret).</summary>
    public const string BasicAuthenticator = "BasicAuthenticator";

    /// <summary>The WSO2 authenticator for the TOTP step.</summary>
    public const string TotpAuthenticator = "totp";

    private static readonly string[] RequestedClaims =
    [
        Wso2Ids.UserNameClaim,
        Wso2Ids.EmailClaim,
        Wso2Ids.FullNameClaim,
        Wso2Ids.RolesClaim,
        IamNames.InstitutionLocalClaim,
    ];

    /// <inheritdoc />
    public string Name => "portal-app";

    /// <inheritdoc />
    public async Task RunAsync(BootstrapState state, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(state);
        var settings = options.Value;

        var app = await applications.EnsureAsync(
            IamNames.PortalApp, IamNames.PortalClientId, Settings(settings), Oidc(settings), CreateOnly(), cancellationToken);
        state.PortalAppId = app.Id;
        state.Record("OIDC app", IamNames.PortalApp, app.Outcome);
        state.GeneratedSettings["Oidc__ClientId"] = app.ClientId;
        state.GeneratedSettings["Oidc__ClientSecret"] = app.ClientSecret;
    }

    /// <summary>Builds the adaptive authentication script (plan §4.5).</summary>
    /// <param name="enforceMfa">Whether approvers and administrators need TOTP.</param>
    /// <param name="alwaysUsers">Users who always need TOTP.</param>
    /// <returns>The script.</returns>
    internal static string AdaptiveScript(bool enforceMfa, IEnumerable<string> alwaysUsers)
    {
        var users = JsonSerializer.Serialize(alwaysUsers.Distinct(StringComparer.OrdinalIgnoreCase).ToArray());
        var roles = JsonSerializer.Serialize(new[] { RoleNames.SupervisorApprover, RoleNames.SystemAdmin });
        var enforce = enforceMfa ? "true" : "false";
        return string.Create(CultureInfo.InvariantCulture, $$"""
            // Generated by regreturns-iam-bootstrap; edits in the Console are overwritten on the next run.
            var enforceForRoles = {{roles}};
            var enforce = {{enforce}};
            var alwaysUsers = {{users}};
            var onLoginRequest = function (context) {
                executeStep(1, {
                    onSuccess: function (context) {
                        var user = context.currentKnownSubject;
                        var needsTotp = alwaysUsers.indexOf(user.username) >= 0 ||
                            (enforce && hasAnyOfTheRolesV2(context, enforceForRoles));
                        if (needsTotp) {
                            executeStep(2);
                        }
                    }
                });
            };
            """);
    }

    private static JsonObject Settings(BootstrapOptions settings) => new()
    {
        ["description"] = "RegReturns web portal (OIDC code flow with PKCE).",
        ["accessUrl"] = settings.PortalBaseUrl!.ToString(),
        ["advancedConfigurations"] = new JsonObject
        {
            // First-party app: no consent screens.
            ["skipLoginConsent"] = true,
            ["skipLogoutConsent"] = true,
        },
        ["claimConfiguration"] = new JsonObject
        {
            ["dialect"] = "LOCAL",
            ["requestedClaims"] = new JsonArray([.. RequestedClaims.Select(uri => new JsonObject
            {
                ["claim"] = new JsonObject { ["uri"] = uri },
                ["mandatory"] = false,
            })]),
            ["subject"] = new JsonObject
            {
                // sub = the WSO2 user id, stable across user name changes.
                ["claim"] = new JsonObject { ["uri"] = Wso2Ids.UserIdClaim },
                ["includeUserDomain"] = false,
                ["includeTenantDomain"] = false,
                ["useMappedLocalSubject"] = false,
            },
        },
        ["authenticationSequence"] = new JsonObject
        {
            ["type"] = "USER_DEFINED",
            ["steps"] = new JsonArray(
                Step(1, BasicAuthenticator),
                Step(2, TotpAuthenticator)),
            ["script"] = AdaptiveScript(settings.EnforceMfa, settings.MfaAlwaysUsers),
            ["subjectStepId"] = 1,
            ["attributeStepId"] = 1,
        },
    };

    private static JsonObject Step(int id, string authenticator) => new()
    {
        ["id"] = id,
        ["options"] = new JsonArray(new JsonObject { ["idp"] = "LOCAL", ["authenticator"] = authenticator }),
    };

    private static JsonObject Oidc(BootstrapOptions settings) => new()
    {
        ["grantTypes"] = new JsonArray("authorization_code"),

        // WSO2 stores one callback; several URLs need a single full-match regex. It also governs post_logout_redirect_uri.
        ["callbackURLs"] = new JsonArray($"regexp=({Escape(settings.RedirectUrl)}|{Escape(settings.PostLogoutRedirectUrl)})"),
        ["allowedOrigins"] = new JsonArray(),
        ["publicClient"] = false,
        ["pkce"] = new JsonObject { ["mandatory"] = true, ["supportPlainTransformAlgorithm"] = false },
        ["accessToken"] = new JsonObject
        {
            ["type"] = "JWT",
            ["userAccessTokenExpiryInSeconds"] = IamNames.AccessTokenSeconds,
            ["applicationAccessTokenExpiryInSeconds"] = IamNames.AccessTokenSeconds,
        },
        ["logout"] = new JsonObject { ["backChannelLogoutUrl"] = settings.EffectiveBackchannelLogoutUrl.ToString() },
    };

    // Roles have the application audience: they belong to the portal and appear in its tokens only.
    private static JsonObject CreateOnly() => new()
    {
        ["associatedRoles"] = new JsonObject { ["allowedAudience"] = "APPLICATION", ["roles"] = new JsonArray() },
    };

    private static string Escape(Uri url) => Regex.Escape(url.ToString());
}
