using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

using RegReturns.IamBootstrap.Steps;

namespace RegReturns.IamBootstrap;

/// <summary>Runs the setup steps in order, logs what changed and writes the generated secrets file.</summary>
/// <param name="steps">The registered steps, in registration order.</param>
/// <param name="options">The tool options.</param>
/// <param name="logger">The logger.</param>
internal sealed partial class BootstrapRunner(
    IEnumerable<IBootstrapStep> steps,
    IOptions<BootstrapOptions> options,
    ILogger<BootstrapRunner> logger)
{
    /// <summary>Runs the named steps (all when <paramref name="only"/> is empty).</summary>
    /// <param name="only">Step names to run, or empty for all.</param>
    /// <param name="envFileOverride">Where to write generated secrets instead of the configured file.</param>
    /// <param name="resetDemoUsers">Whether existing demo users get their password and TOTP reset.</param>
    /// <param name="cancellationToken">Cancels the run.</param>
    /// <returns>The shared state, for tests.</returns>
    public async Task<BootstrapState> RunAsync(
        IReadOnlyCollection<string> only, string? envFileOverride, bool resetDemoUsers, CancellationToken cancellationToken)
    {
        var settings = options.Value;

        var path = Path.GetFullPath(envFileOverride ?? settings.EnvFilePath);
        var state = new BootstrapState { ResetDemoUsers = resetDemoUsers };
        foreach (var (key, value) in DotEnvFile.Read(path))
        {
            state.ExistingSettings[key] = value;
        }

        foreach (var step in steps.Where(s => only.Count == 0 || only.Contains(s.Name)))
        {
            LogStep(logger, step.Name);
            await step.RunAsync(state, cancellationToken);
        }

        foreach (var (kind, name, outcome) in state.Changes.Where(c => c.Outcome != Outcome.Unchanged))
        {
            LogChange(logger, kind, name, outcome);
        }

        var created = state.Changes.Count(c => c.Outcome == Outcome.Created);
        var updated = state.Changes.Count(c => c.Outcome == Outcome.Updated);
        var unchanged = state.Changes.Count - created - updated;
        LogSummary(logger, created, updated, unchanged);

        if (state.GeneratedSettings.Count > 0)
        {
            DotEnvFile.Write(path, state.GeneratedSettings, "Generated by regreturns-iam-bootstrap. Secrets: never commit or share.");
            LogEnvFile(logger, state.GeneratedSettings.Count, path);
        }

        return state;
    }

    [LoggerMessage(EventId = 4101, Level = LogLevel.Information, Message = "Step {Step}")]
    private static partial void LogStep(ILogger logger, string step);

    [LoggerMessage(EventId = 4102, Level = LogLevel.Information, Message = "{Kind} {Name}: {Outcome}")]
    private static partial void LogChange(ILogger logger, string kind, string name, Outcome outcome);

    [LoggerMessage(EventId = 4103, Level = LogLevel.Information, Message = "WSO2 setup complete: {Created} created, {Updated} updated, {Unchanged} unchanged")]
    private static partial void LogSummary(ILogger logger, int created, int updated, int unchanged);

    [LoggerMessage(EventId = 4104, Level = LogLevel.Information, Message = "Wrote {Count} generated setting(s) to {Path}")]
    private static partial void LogEnvFile(ILogger logger, int count, string path);
}
