using System.Net;
using System.Text;
using System.Text.Json;

using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

using RegReturns.Domain.Auditing;
using RegReturns.Domain.Insights;
using RegReturns.Domain.Submissions;
using RegReturns.Infrastructure.Ai;
using RegReturns.Infrastructure.Persistence.Seeding;
using RegReturns.IntegrationTests.Hosting;
using RegReturns.IntegrationTests.Infrastructure;

namespace RegReturns.IntegrationTests.Web;

/// <summary>
/// Advisory insights on the review page (ADR 0030): fixed rules stand in without an API key, an AI answer is shown
/// encoded and labelled, a failed call falls back and is tried again, every generation is audited with the digests of
/// what was sent and written, and the payload never carries the bank's name, people or justifications. The Anthropic
/// API is replaced by a stub; nothing leaves the test.
/// </summary>
[Collection(HostedAppsDefinition.Name)]
public sealed class InsightPagesTests : IClassFixture<PortalDatabaseFixture>, IDisposable
{
    private const string AiHeadline = "<script>alert(1)</script> Deposits shifted towards time deposits.";

    private static readonly string[] Observations = ["Time deposits rose."];
    private static readonly string[] Questions = ["Why did time deposits rise?"];

    private readonly string _connectionString;
    private readonly WebApplicationFactory<Program> _noKey;
    private readonly WebApplicationFactory<Program> _withKey;
    private readonly StubAnthropic _anthropic = new();

    public InsightPagesTests(PortalDatabaseFixture database)
    {
        _connectionString = database.ConnectionString;
        _noKey = PortalHost.Create(_connectionString, settings: new Dictionary<string, string?> { ["Ai:Anthropic:ApiKey"] = string.Empty });
        _withKey = PortalHost.Create(
            _connectionString,
            services => services.AddHttpClient(AnthropicInsightNarrator.HttpClientName).ConfigurePrimaryHttpMessageHandler(() => _anthropic),
            new Dictionary<string, string?> { ["Ai:Anthropic:ApiKey"] = "sk-ant-integration-test", ["Ai:Anthropic:MaxRetries"] = "0" });
    }

    private static CancellationToken Ct => TestContext.Current.CancellationToken;

    [Fact]
    public async Task Without_a_key_fixed_rules_write_the_insight_and_nothing_is_sent()
    {
        var id = await HarbourlineNplJumpAsync();
        using var reviewer = await new SupervisionPortal(_noKey, _connectionString).ReviewerAsync();
        var before = await PortalForms.GetTextAsync(reviewer, Page(id));
        before.ShouldContain("Advisory insight");
        before.ShouldContain("No API key is configured, so insights are written by fixed rules and nothing leaves the portal.");

        var response = await PortalForms.PostAsync(reviewer, Page(id), $"{Page(id)}/insight");

        response.Headers.Location.ShouldNotBeNull().OriginalString.ShouldBe($"{Page(id)}#insight");
        var page = await PortalForms.FollowAsync(reviewer, response);
        page.ShouldContain("Insight generated by fixed rules. No API key is configured for the AI provider.");
        page.ShouldContain("Rule-based, advisory");
        page.ShouldContain("Non-performing loan ratio rose by");
        page.ShouldContain("The bank justified this warning.");
        page.ShouldContain("Nothing was sent.");
        page.ShouldContain("Refresh insight");
        var insight = (await InsightsAsync(id)).ShouldHaveSingleItem();
        (insight.Provider, insight.FallbackReason).ShouldBe((InsightProvider.RuleBased, InsightFallbackReason.NotConfigured));
        await ShouldCarryNoBankTextAsync(id, insight.Payload);
        var entry = (await AuditEntriesAsync(id)).ShouldHaveSingleItem();
        entry.Sequence.ShouldBe(insight.AuditSequence);
        entry.Details.ShouldNotBeNull().ShouldContain("payload not sent");
        entry.Details.ShouldContain($"payload sha256 {insight.InputSha256}; content sha256 {insight.OutputSha256}");
        page.ShouldContain($"audit entry {entry.Sequence}");
    }

    [Fact]
    public async Task Generating_again_without_a_change_shows_the_same_insight_and_records_nothing_new()
    {
        var id = await SubmittedAsync(DemoBank.Crestmont, MdaTemplate.Code);
        using var approver = await new SupervisionPortal(_noKey, _connectionString).ApproverAsync();
        await PortalForms.PostAsync(approver, Page(id), $"{Page(id)}/insight");

        var again = await PortalForms.PostAsync(approver, Page(id), $"{Page(id)}/insight");

        (await PortalForms.FollowAsync(approver, again)).ShouldContain("Nothing has changed since the last insight, so it is shown again.");
        (await InsightsAsync(id)).Count.ShouldBe(1);
        (await AuditEntriesAsync(id)).Count.ShouldBe(1);
    }

    [Fact]
    public async Task An_ai_insight_is_labelled_encoded_and_audited_with_what_was_sent()
    {
        var id = await SubmittedAsync(DemoBank.Northgate, MdaTemplate.Code);
        _anthropic.Respond = _ => Answer(AiHeadline);
        using var reviewer = await new SupervisionPortal(_withKey, _connectionString).ReviewerAsync();
        (await PortalForms.GetTextAsync(reviewer, Page(id))).ShouldContain("Written by Claude (claude-opus-5-5) through the Anthropic API");

        var response = await PortalForms.PostAsync(reviewer, Page(id), $"{Page(id)}/insight");

        var html = await PortalForms.GetHtmlAsync(reviewer, PortalForms.RedirectPath(response));
        html.ShouldContain("Insight generated.");
        html.ShouldContain("AI-generated, advisory");
        html.ShouldContain("&lt;script&gt;alert(1)&lt;/script&gt; Deposits shifted towards time deposits.");
        html.ShouldNotContain("<script>alert(1)</script>");
        var sent = _anthropic.Bodies.ShouldHaveSingleItem();
        var insight = (await InsightsAsync(id)).ShouldHaveSingleItem();
        (insight.Provider, insight.Model, insight.FallbackReason).ShouldBe((InsightProvider.Anthropic, "claude-opus-5-5", (InsightFallbackReason?)null));
        JsonDocument.Parse(sent).RootElement.GetProperty("messages")[0].GetProperty("content").GetString().ShouldBe(insight.Payload);
        await ShouldCarryNoBankTextAsync(id, sent);
        (await AuditEntriesAsync(id)).ShouldHaveSingleItem().Details.ShouldNotBeNull()
            .ShouldContain("written by Anthropic claude-opus-5-5; payload sent to Anthropic claude-opus-5-5");
    }

    [Fact]
    public async Task A_failed_call_falls_back_to_fixed_rules_and_the_next_request_asks_again()
    {
        var id = await SubmittedAsync(DemoBank.LotusUnion, MlrTemplate.Code);
        _anthropic.Respond = _ => new HttpResponseMessage(HttpStatusCode.InternalServerError)
        {
            Content = new StringContent("""{"type":"error","error":{"type":"api_error","message":"Internal error"}}""", Encoding.UTF8, "application/json"),
        };
        using var approver = await new SupervisionPortal(_withKey, _connectionString).ApproverAsync();

        var failed = await PortalForms.PostAsync(approver, Page(id), $"{Page(id)}/insight");

        var page = await PortalForms.FollowAsync(approver, failed);
        page.ShouldContain("Insight generated by fixed rules. The AI provider could not be reached.");
        page.ShouldContain("This exact document was sent to the AI provider, which gave no usable answer");
        (await AuditEntriesAsync(id)).ShouldHaveSingleItem().Details.ShouldNotBeNull()
            .ShouldContain("in place of Anthropic claude-opus-5-5 (ProviderUnavailable); payload sent to Anthropic claude-opus-5-5");

        _anthropic.Respond = _ => Answer("LCR is comfortably above the minimum.");
        var retried = await PortalForms.PostAsync(approver, Page(id), $"{Page(id)}/insight");

        (await PortalForms.FollowAsync(approver, retried)).ShouldContain("LCR is comfortably above the minimum.");
        (await InsightsAsync(id)).Select(i => i.Provider).ShouldBe([InsightProvider.RuleBased, InsightProvider.Anthropic]);
        (await AuditEntriesAsync(id)).Count.ShouldBe(2);
    }

    [Fact]
    public async Task Bank_staff_and_the_auditor_cannot_generate_insights()
    {
        var id = await HarbourlineNplJumpAsync();
        var recorded = (await AuditEntriesAsync(id)).Count;
        using var maker = await new BankPortal(_noKey, _connectionString).MakerAsync();
        using var auditor = await new SupervisionPortal(_noKey, _connectionString).AuditorAsync();
        var token = PortalForms.TokenFrom(await PortalForms.GetHtmlAsync(maker, "/bank"));

        using var form = new FormUrlEncodedContent([new(PortalForms.TokenField, token)]);
        (await maker.PostAsync(new Uri($"{Page(id)}/insight", UriKind.Relative), form, Ct)).StatusCode.ShouldBe(HttpStatusCode.Forbidden);
        (await auditor.GetAsync(new Uri(Page(id), UriKind.Relative), Ct)).StatusCode.ShouldBe(HttpStatusCode.Forbidden);
        (await AuditEntriesAsync(id)).Count.ShouldBe(recorded);
    }

    public void Dispose()
    {
        _noKey.Dispose();
        _withKey.Dispose();
        _anthropic.Dispose();
    }

    private static string Page(Guid id) => $"/supervision/returns/{id}";

    private static HttpResponseMessage Answer(string headline)
    {
        var text = JsonSerializer.Serialize(new { headline, observations = Observations, questions = Questions });
        var message = JsonSerializer.Serialize(new Dictionary<string, object?>
        {
            ["id"] = "msg_integration",
            ["type"] = "message",
            ["role"] = "assistant",
            ["model"] = "claude-opus-5-5",
            ["content"] = new[] { new Dictionary<string, object?> { ["type"] = "text", ["text"] = text } },
            ["stop_reason"] = "end_turn",
            ["stop_sequence"] = null,
            ["usage"] = new Dictionary<string, object?> { ["input_tokens"] = 900, ["output_tokens"] = 120 },
        });
        return new HttpResponseMessage(HttpStatusCode.OK) { Content = new StringContent(message, Encoding.UTF8, "application/json") };
    }

    private async Task<Guid> HarbourlineNplJumpAsync()
    {
        await using var context = SqlServerFixture.CreateContext(_connectionString);
        // The seeded story's highest non-performing loan ratio is the month of the jump (DemoScenario).
        return await context.Submissions
            .Where(s => s.Status == SubmissionStatus.Approved
                && context.Institutions.Any(i => i.Id == s.InstitutionId && i.Code == DemoBank.Harbourline))
            .SelectMany(s => s.Values.Where(v => v.FieldCode == MdaTemplate.NplRatio), (s, v) => new { s.Id, v.NumericValue })
            .OrderByDescending(x => x.NumericValue)
            .Select(x => x.Id)
            .FirstAsync(Ct);
    }

    private async Task<Guid> SubmittedAsync(string bankCode, string returnTypeCode)
    {
        await using var context = SqlServerFixture.CreateContext(_connectionString);
        return await context.Submissions
            .Where(s => s.Status == SubmissionStatus.Submitted
                && context.Institutions.Any(i => i.Id == s.InstitutionId && i.Code == bankCode)
                && context.ReturnTypes.Any(r => r.Id == s.ReturnTypeId && r.Code == returnTypeCode))
            .Select(s => s.Id)
            .SingleAsync(Ct);
    }

    private async Task<List<ReturnInsight>> InsightsAsync(Guid submissionId)
    {
        await using var context = SqlServerFixture.CreateContext(_connectionString);
        return await context.ReturnInsights.AsNoTracking()
            .Where(i => i.SubmissionId == submissionId)
            .OrderBy(i => i.CreatedAt)
            .ToListAsync(Ct);
    }

    private async Task<List<AuditEntry>> AuditEntriesAsync(Guid submissionId)
    {
        await using var context = SqlServerFixture.CreateContext(_connectionString);
        var entityId = submissionId.ToString();
        return await context.AuditEntries.AsNoTracking()
            .Where(e => e.Action == AuditAction.InsightGenerated && e.EntityId == entityId)
            .OrderBy(e => e.Sequence)
            .ToListAsync(Ct);
    }

    private async Task ShouldCarryNoBankTextAsync(Guid submissionId, string sent)
    {
        await using var context = SqlServerFixture.CreateContext(_connectionString);
        var submission = await context.Submissions.AsNoTracking()
            .Include(s => s.Findings)
            .Include(s => s.Events)
            .SingleAsync(s => s.Id == submissionId, Ct);
        var bank = await context.Institutions.AsNoTracking().SingleAsync(i => i.Id == submission.InstitutionId, Ct);
        sent.ShouldNotContain(bank.Name);
        sent.ShouldNotContain($"\"{bank.Code}\"");
        sent.ShouldNotContain(submissionId.ToString());
        foreach (var text in submission.Findings.Select(f => f.Justification).Concat(submission.Events.Select(e => e.Comment)).OfType<string>())
        {
            sent.ShouldNotContain(text);
        }

        sent.ShouldNotContain("@");
    }

    /// <summary>Stands in for the Anthropic API: answers with <see cref="Respond"/> and keeps every request body.</summary>
    private sealed class StubAnthropic : HttpMessageHandler
    {
        public Func<HttpRequestMessage, HttpResponseMessage> Respond { get; set; } =
            _ => throw new InvalidOperationException("No answer configured.");

        public List<string> Bodies { get; } = [];

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            Bodies.Add(request.Content is null ? string.Empty : await request.Content.ReadAsStringAsync(cancellationToken));
            return Respond(request);
        }
    }
}
